// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package sqlc

import (
	"context"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateDomain(ctx context.Context, name string) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain, name)
	var i Domain
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getDomainByName = `-- name: GetDomainByName :one
SELECT id, name, created_at
FROM DOMAINS
where name = $1
`

func (q *Queries) GetDomainByName(ctx context.Context, name string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByName, name)
	var i Domain
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
