// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Domain struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Mailbox struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID         pgtype.UUID        `json:"id"`
	MailboxID  pgtype.UUID        `json:"mailbox_id"`
	MessageID  pgtype.Text        `json:"message_id"`
	Sender     string             `json:"sender"`
	Recipient  string             `json:"recipient"`
	Subject    pgtype.Text        `json:"subject"`
	BodyText   pgtype.Text        `json:"body_text"`
	BodyHtml   pgtype.Text        `json:"body_html"`
	IsRead     pgtype.Bool        `json:"is_read"`
	IsFlagged  pgtype.Bool        `json:"is_flagged"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                    pgtype.UUID        `json:"id"`
	DomainID              pgtype.UUID        `json:"domain_id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	EncryptedImapPassword []byte             `json:"encrypted_imap_password"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}
