// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Domain struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ImapHost           string             `json:"imap_host"`
	ImapUsernameFormat string             `json:"imap_username_format"`
	ImapPort           int32              `json:"imap_port"`
	ImapEncryption     string             `json:"imap_encryption"`
	SmtpHost           string             `json:"smtp_host"`
	SmtpPort           int32              `json:"smtp_port"`
	SmtpEncryption     string             `json:"smtp_encryption"`
	AllowInsecureTls   bool               `json:"allow_insecure_tls"`
}

type Mailbox struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID         pgtype.UUID        `json:"id"`
	MailboxID  pgtype.UUID        `json:"mailbox_id"`
	MessageID  pgtype.Text        `json:"message_id"`
	Sender     string             `json:"sender"`
	Recipient  string             `json:"recipient"`
	Subject    pgtype.Text        `json:"subject"`
	BodyText   pgtype.Text        `json:"body_text"`
	BodyHtml   pgtype.Text        `json:"body_html"`
	IsRead     pgtype.Bool        `json:"is_read"`
	IsFlagged  pgtype.Bool        `json:"is_flagged"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	IpAddress  string             `json:"ip_address"`
	UserAgent  string             `json:"user_agent"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                    pgtype.UUID        `json:"id"`
	DomainID              pgtype.UUID        `json:"domain_id"`
	Email                 string             `json:"email"`
	EncryptedImapPassword []byte             `json:"encrypted_imap_password"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	AuthStatus            string             `json:"auth_status"`
}
