// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (domain_id, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, domain_id, email, password_hash, created_at
`

type CreateUserParams struct {
	DomainID     pgtype.UUID `json:"domain_id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
}

type CreateUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	DomainID     pgtype.UUID        `json:"domain_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.DomainID, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, domain_id, email, password_hash, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	DomainID     pgtype.UUID        `json:"domain_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, domain_id, email, password_hash, created_at
FROM users
WHERE id = $1
`

type GetUserByIdRow struct {
	ID           pgtype.UUID        `json:"id"`
	DomainID     pgtype.UUID        `json:"domain_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserImapPassword = `-- name: UpdateUserImapPassword :exec
UPDATE users
SET encrypted_imap_password = $1
WHERE id = $2
`

type UpdateUserImapPasswordParams struct {
	EncryptedImapPassword []byte      `json:"encrypted_imap_password"`
	ID                    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserImapPassword(ctx context.Context, arg UpdateUserImapPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserImapPassword, arg.EncryptedImapPassword, arg.ID)
	return err
}
